#!/bin/zsh
set -eux

systemd_dir=${0:a:h}/systemd/
hostname=$(hostname)

LANG=C.utf8 stack install . xmobar --flag xmobar:with_datezone

cd ../

ln -sfv .xmonad/.xsession .
ln -sfv .xmonad/.xmobarrc-$hostname .xmobarrc

cd ~/.config/systemd/user/
for f in $(ls $systemd_dir)
do
  # xkbsetはindigo向けのパッチなのでそこだけに貼ります。
  if [[ $f == xkbset* ]]; then
    if [[ $hostname == indigo ]]; then
      ln -sfv $(realpath --relative-to=. $systemd_dir/$f) .
    fi
  else
    ln -sfv $(realpath --relative-to=. $systemd_dir/$f) .
  fi
done
