name: xmonad-launch
version: 0.1.0
synopsis: It is my xmonad and xmobar setting
github: ncaq/.xmonad
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -O2

dependencies:
  - base
  - containers
  - directory
  - gi-glib
  - gi-gtk
  - hostname
  - regex-tdfa
  - string-transform
  - time
  - xmonad
  - xmonad-contrib

executables:
  xmonad-launch:
    main: Main.hs
    source-dirs: src
