name: xmonad-launch
version: 0.1.0.0
synopsis: It is my xmonad and xmobar setting
github: ncaq/.xmonad
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

language: GHC2021

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base
  - containers
  - convertible
  - directory
  - gi-glib
  - gi-gtk
  - hostname
  - regex-tdfa
  - text
  - time
  - xmonad
  - xmonad-contrib

library:
  source-dirs: src

executables:
  xmonad-launch:
    main: Main.hs
    source-dirs: app
    dependencies:
      - xmonad-launch

    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N4
