name: xmonad-launch
version: 0.1.0.0
synopsis: It is my xmonad and xmobar setting
github: ncaq/.xmonad
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

language: GHC2024

default-extensions:
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -j

dependencies:
  - base
  - containers
  - convertible
  - directory
  - gi-glib
  - gi-gtk3
  - hostname
  - process
  - text
  - time
  - xmobar
  - xmonad
  - xmonad-contrib

library:
  source-dirs: src

executables:
  xmonad-launch:
    main: Main.hs
    source-dirs: app/XMonad
    dependencies:
      - xmonad-launch

    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  xmobar-launch:
    main: Main.hs
    source-dirs: app/Xmobar
    dependencies:
      - xmonad-launch

    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N2
