name: xmonad-ncaq
version: 0.1.0
synopsis: It is my xmonad and xmobar setting
github: ncaq/.xmonad
author: ncaq
maintainer: ncaq@ncaq.net
copyright: © ncaq
license: MIT

ghc-options:
  - -Wall
  # - -Wall-missed-specialisations
  - -Widentities
  # - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissed-specialisations
  # - -Wmissing-export-lists
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  # - -Wmissing-import-lists
  # - -Wmissing-local-signatures
  # - -Wmonomorphism-restriction
  # - -Wpartial-fields
  - -Wredundant-constraints
  - -Wcompat
  - -O2

dependencies:
  - base
  - containers
  - directory
  - hostname
  - regex-tdfa
  - time
  - xmonad
  - xmonad-contrib

executables:
  xmonad-ncaq:
    main: Main.hs
    source-dirs: src
